name: "Run Tests"

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    name: "Project Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ["ethers", "viem"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          key: api-result-cache
          path: ./.cache
      - run: npm ci
      - name: Run tests with ${{ matrix.provider }}
        run: npm test
        env:
          PROVIDER: ${{ matrix.provider }}
          ONLINE: 1
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
