name: "Run Tests"

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: "Project Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ["ethers", "viem", "web3"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - uses: actions/cache@v3
        with:
          key: api-result-cache
          path: ./.cache
      - run: pnpm install
      - name: Run tests with ${{ matrix.provider }}
        run: pnpm test
        env:
          PROVIDER: ${{ matrix.provider }}
          ONLINE: 1
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
